### ISSUE TITLE
No longer works on GNOME 3.34

### ISSUE THREAD

**Issue by elegantMarigolds** [armonge/gnome-shell-extension-focusli#23]
When installing on GNOME 3.34 error message appears

**Comment by armonge** [comment]
Hi @rileyball do you have any logs you can share? At the moment i don't have 3.34 yet but i can probably work on it over the weekend

**Comment by rileyball** [comment]
> Hi @rileyball do you have any logs you can share? At the moment i don't have 3.34 yet but i can probably work on it over the weekend

I'm kinda new to GNOME. Where would logs for extensions be?

**Comment by elegantMarigolds** [comment]
> Hi @rileyball do you have any logs you can share? At the moment i don't have 3.34 yet but i can probably work on it over the weekend

https://pastebin.com/1K2cbiW9
Here you go!

Edit: Also when viewing the errors in looking glass it says this.setLoading is not a function

**Comment by elegantMarigolds** [comment]
Works perfectly now. Thanks
